name: Debug and Resolve Git Issues

on:
  workflow_dispatch:

jobs:
  resolve-git-issues:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clear Git Cache
      run: |
        git rm -r --cached .
        git add .
        git commit -m "Cleared Git cache and re-added files"

    - name: Force File Modification
      run: |
        find . -type f -exec touch {} +
        git add .
        git commit --allow-empty -m "Force detection of file changes"

    - name: Debug `.gitignore`
      run: |
        if [ -f .gitignore ]; then
          echo "Checking .gitignore rules:"
          cat .gitignore
        else
          echo "No .gitignore file found."
        fi

    - name: Debug Git Status
      run: |
        git status
        echo "Git tracked files:"
        git ls-tree -r HEAD --name-only

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit --allow-empty -m "Resolved Git working tree issues"
        git push origin main
