name: Debug and Force Commit

on:
  workflow_dispatch:

jobs:
  debug-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Ensure Manuscript Exists and Backup
      run: |
        # Verify if the manuscript exists and create a backup
        if [ ! -f docs/manuscript.md ]; then
          echo "Error: manuscript.md file not found in docs directory."
          exit 1
        fi
        cp docs/manuscript.md docs/manuscript_backup.md
        echo "Backup created: docs/manuscript_backup.md"

    - name: Modify Manuscript
      run: |
        # Make a small modification to force a change
        echo "## Last Updated: $(date)" >> docs/manuscript.md
        echo "Manuscript modified with timestamp."

    - name: Display Manuscript for Debugging
      run: |
        echo "File content after modification:"
        cat docs/manuscript.md

    - name: Upload Manuscript for Debugging
      uses: actions/upload-artifact@v3
      with:
        name: modified-manuscript
        path: docs/manuscript.md

    - name: Debug Git Status
      run: |
        # Check the status of the repository
        git status
        echo "Git ignore file content (if exists):"
        if [ -f .gitignore ]; then
          cat .gitignore
        else
          echo "No .gitignore file found."
        fi

    - name: Force Add and Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Refresh the index and stage all changes
        git update-index --refresh
        git add -A

        # Commit changes or allow an empty commit if nothing changed
        git commit --allow-empty -m "Force commit: updated manuscript"
        git push origin main
