name: Debug and Resolve Git Issues

on:
  workflow_dispatch:

jobs:
  resolve-git-issues:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug and Resolve Git Issues
      run: |
        # Clear Git cache
        git rm -r --cached .
        git add .

        # Force file modification to ensure Git detects changes
        find . -type f -exec touch {} +
        git add .

        # Display .gitignore rules for debugging
        if [ -f .gitignore ]; then
          echo "Checking .gitignore rules:"
          cat .gitignore
        else
          echo "No .gitignore file found."
        fi

        # Debug Git status and tracked files
        git status
        echo "Git tracked files:"
        git ls-tree -r HEAD --name-only

        # Commit and push changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit --allow-empty -m "Resolved Git working tree issues"
        git push origin main
