name: Add Math Tags to Manuscript

on:
  workflow_dispatch:

jobs:
  add-math-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure manuscript exists and create a backup
      run: |
        # Check if the manuscript file exists
        if [ ! -f docs/manuscript.md ]; then
          echo "Error: manuscript.md file not found in docs directory."
          exit 1
        fi

        # Create a backup of the manuscript
        cp docs/manuscript.md docs/manuscript_backup.md
        echo "Backup created: manuscript_backup.md"

    - name: Add math tags to symbols and equations
      run: |
        # Add math tags to inline equations (e.g., \(E=mc^2\) -> $E=mc^2$)
        sed -i -E 's/\\(([^)]+)\\)/$\1$/g' docs/manuscript.md

        # Add math tags to block equations (e.g., \[E=mc^2\] -> $$E=mc^2$$)
        sed -i -E 's/^\\\[(.+)\]$/$$\1$$/g' docs/manuscript.md

        # Escape special characters (_ and ^) for Markdown rendering
        sed -i -E 's/\\([_^])/\\\1/g' docs/manuscript.md

        echo "Math tags added successfully."

    - name: Commit updated manuscript
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/manuscript.md
        git commit -m "Added math tags to symbols and equations"
        git push
