name: Debug and Force Commit

on:
  workflow_dispatch:

jobs:
  force-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Ensure Manuscript Exists and Backup
      run: |
        if [ ! -f docs/manuscript.md ]; then
          echo "Error: manuscript.md file not found in docs directory."
          exit 1
        fi
        cp docs/manuscript.md docs/manuscript_backup.md

    - name: Modify Manuscript
      run: |
        # Modify the manuscript with dummy data to force a change
        echo "## Last Updated: $(date)" >> docs/manuscript.md

    - name: Force Git to Recheck File Changes
      run: |
        git update-index --refresh
        git status

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit --allow-empty -m "Force commit to update repository"
        git push origin main 
