name: Add Math Tags to Manuscript

on:
  workflow_dispatch:

jobs:
  add-math-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure manuscript exists and create a backup
      run: |
        if [ ! -f docs/manuscript.md ]; then
          echo "Error: manuscript.md file not found in docs directory."
          exit 1
        fi
        cp docs/manuscript.md docs/manuscript_backup.md

    - name: Add math tags to symbols and equations
      run: |
        sed -i -E 's/\\(([^)]+)\\)/$\1$/g' docs/manuscript.md
        sed -i -E 's/^\\\[(.+)\]$/$$\1$$/g' docs/manuscript.md
        sed -i -E 's/\\([_^])/\\\1/g' docs/manuscript.md

    - name: Display Modified Manuscript
      run: cat docs/manuscript.md

    - name: Force Git Changes
      run: echo "## Last Updated: $(date)" >> docs/manuscript.md

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Added math tags and updated manuscript"
        git push origin main
